version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run:
          name: rodando
          command:
            python app.py
      - run:
          name: run tests
          command:
            python app.py test
